### ISSUE TITLE
Buttons only show hover cursor when mousing over text, more contrast on hover

### ISSUE THREAD

**Issue by LucyLetour** [RUCOGS/rucogs.github.io#3]
Buttons on the site (discord + mailing list button on homepage, view project button on project page) only show hover cursor when hovering over the text on the button despite the fact that the button is clickable even when not directly over the text. Buttons also should have more contrast to indicate hover, this could also be a visual transformation (squaring corners or whatnot)

- [x] Hover cursor on whole button
- [ ] Greater contrast between hovered/not

**Comment by Atlinx** [comment]
Hover for regular buttons accounted for with #12

**Comment by Atlinx** [comment]
Not sure how we can have a greater contrast between the hover and default state. If we make the color darker, it will start to blend into the red background, as they begin to take on the same darkness level.

A drop shadow could provide contrast with the button's background though I'm not a big fan of making a drop shadow buttons because it conflicts with the flat, modern-looking aesthetic.
